openapi: 3.0.0
info:
  title: MWE
  version: 1.0.0
paths:
  '/upload':
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: File upload successful
