openapi: 3.0.0
info:
  title: MWE
  version: 1.0.0
paths:
  '/upload':
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        '201':
          description: File upload successful
  '/download':
    get:
      summary: Download a file
      parameters:
        - name: path
          in: query
          description: Absolute path to destination
          schema:
            type: string
          allowReserved: true
          required: true
      responses:
        '200':
          description: Returns the file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
