# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


function upload_post_read(handler)
    function upload_post_read_handler(req::HTTP.Request)
        openapi_params = Dict{String,Any}()
        openapi_params["body"] = OpenAPI.Servers.to_param_type(String, String(req.body))
        req.context[:openapi_params] = openapi_params

        return handler(req)
    end
end

function upload_post_validate(handler)
    function upload_post_validate_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        
        return handler(req)
    end
end

function upload_post_invoke(impl; post_invoke=nothing)
    function upload_post_invoke_handler(req::HTTP.Request)
        openapi_params = req.context[:openapi_params]
        ret = impl.upload_post(req::HTTP.Request, openapi_params["body"];)
        resp = OpenAPI.Servers.server_response(ret)
        return (post_invoke === nothing) ? resp : post_invoke(req, resp)
    end
end


function registerDefaultApi(router::HTTP.Router, impl; path_prefix::String="", optional_middlewares...)
    HTTP.register!(router, "POST", path_prefix * "/upload", OpenAPI.Servers.middleware(impl, upload_post_read, upload_post_validate, upload_post_invoke; optional_middlewares...))
    return router
end
